## File: cppeurope/docker-compose.yml 
services:
  user-backend:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./user-backend:/usr/src/app
    env_file:
      - ./user-backend/.env.production
    environment:
      NODE_ENV: production
      ALLOWED_ORIGINS: https://cppeurope.net,https://www.cppeurope.net,http://localhost:8082
    command: bash -c "node server.prod.js"
    depends_on:
      - mariadb
    restart: always
    ports:
      - "7003:7003"

  presse-generale-backend:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./presseGenerale-backend:/usr/src/app
    env_file:
      - ./presseGenerale-backend/.env.production
    environment:
      NODE_ENV: production
      ALLOWED_ORIGINS: https://cppeurope.net,https://www.cppeurope.net,http://localhost:8082
    command: bash -c "npm install && node server.prod.js"
    depends_on:
      - mariadb
    restart: always
    ports:
      - "7006:7006"

  presse-locale-backend:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./presseLocale-backend:/usr/src/app
    env_file:
      - ./presseLocale-backend/.env.production
    environment:
      NODE_ENV: production
      DB_NAME: user_prod_cppeurope_v1
      PORT: 7005
      ALLOWED_ORIGINS: https://cppeurope.net,https://www.cppeurope.net,http://localhost:8082
    command: bash -c "npm install && npx sequelize-cli db:migrate && node server.prod.js"
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_DATABASE: user_prod_cppeurope_v1
      MARIADB_USER:   c
      MARIADB_PASSWORD: CppEurope@2025!
      MARIADB_ROOT_PASSWORD: RootPass@2025!
    volumes:
      - cppeurope-db-data:/var/lib/mysql
    ports:
      - "3308:3306"

  nginx:
    image: nginx:stable
    depends_on:
      - user-backend
      - presse-generale-backend
      - presse-locale-backend
    ports:
      - "8082:80"

    volumes:
      - ./nginx:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./frontend/build:/usr/share/nginx/html

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - mariadb
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

   
volumes:
  cppeurope-db-data: