version: "3.9"
services:
  presseLocale-backend:
    image: node:18-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install --only=production && node server.prod.js"
    ports:
      - "127.0.0.1:7005:7005"
    env_file: .env.production
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: presse_locale_prod_cppeurope_v1
      MARIADB_USER: c
      MARIADB_PASSWORD: CppEurope@2025!
      MARIADB_ROOT_PASSWORD: RootPass@2025!
    volumes:
      - presseLocale-db-data:/var/lib/mysql
    ports:
      - "3310:3306"

volumes:
  presseLocale-db-data:
